### ISSUE TITLE
Region folding 

### ISSUE THREAD

**Issue by stevdompl** [doublefint/vscode-pgsql#15]
Hi,

I would like to ask if there is a chance of adding support for region folding in the `pgsql` language grammar, I tried doing it myself, but couldn't get it working.

At work I use PHPStorm and they fold these blocks in SQL:
```sql
--region {NAME}
...
--endregion

-- region {NAME}
...
-- endregion

--#region {NAME}
...
--#endregion
```
I've tested some variations of the above and came up with the following regular expression patterns (hope it helps):
    - start pattern: `^--(\s+|[#-][\s#-]*)?region[\s]*(?<NAME>.+?)?[\s]*$`
    - end pattern: `^--(\s+|[#-][\s#-]*)?endregion`

Thanks

**Comment by doublefint** [comment]
Hi, Stefan! Like this one?
https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder

**Comment by stevdompl** [comment]
Tried that extension, it does not work with this `pgsql` (there are some problems with other languages as well) or  my custom configuration was wrong

**Comment by stevdompl** [comment]
I tried again with that extension (maptz.regionfolder) and managed to get it working. Here's the part I added to `settings.json` 
```json
    "maptz.regionfolder": {
        "[pgsql]": {
            "foldEnd": "",
            "foldEndRegex": "^--(?:\\s+|[#-][\\s#-]*)?endregion",
            "foldStart": "[NAME]",
            "foldStartRegex": "^--(?:\\s+|[#-][\\s#-]*)?region[\\s]*(.+?)?[\\s]*$",
            "disableFolding": false,
        }
    },
```
