### ISSUE TITLE
Command 'pgsql.run' not found

### ISSUE THREAD

**Issue by incompletude** [doublefint/vscode-pgsql#3]
I have pgAdmin installed on a Windows 10 x64 machine. The folder C:\Program Files (x86)\pgAdmin 4\v2\runtime contains psql.exe, pg_restore.exe, and other client application tools. The folder was added to the PATH variable correctly, psql works globally in the command prompt, but vscode-pgsql still throws a command 'pgsql.run' not found when executed.

Am I missing something here?

Thanks.

**Comment by hubertstrk** [comment]
Just a note: on my machine (Windows 10 x64) _psql.exe_ is located under the path _C:\ProgramFiles\PostgreSQL\9.6\bin_. This is also the location where my path variable points to. The folder _C:\Program Files (x86)\pgAdmin 4\v1\runtime_ does not contain _psql.exe_. Maybe this helps.

**Comment by doublefint** [comment]
@incompletude, I checked your case - Windows 10x64 and C:\Program Files (x86)\pgAdmin 4\v2\runtime in PATH - it works. Can you start ( or restart ) VS Code, open new terminal window and type *psql*?

**Comment by incompletude** [comment]
@hubertstrk, I'm using docker, my machine does not contain a C:\ProgramFiles\PostgreSQL\9.6\bin folder. Maybe because I'm using pgAdmin 4 v2, the runtime folder does contain the client application tools.

@doublefint, I can confirm psql is avaliable at every location by typing psql in the command prompt. It also works properly inside vscode terminal, and the same error is thrown after vscode and machine restart.

Any way to debug this?

**Comment by doublefint** [comment]
@incompletude,  
>but vscode-pgsql still throws a **command 'pgsql.run' not found** when executed.

How do you install plugin ( which version ) and run it? Can you copy exact message from VS Code? You current message about not installed plugin ( the command provided by plugin is not available ) 
>Any way to debug this?

You can clone this repo, enter in folder with repo, install modules ( type "npm install" ) and open it with VS Code, than run plugin in debug mode ( press F5 ). The code what you need is [here](https://github.com/doublefint/vscode-pgsql/blob/master/extension/commands.js#L52)

**Comment by incompletude** [comment]
I have installed it using the vscode extensions market place.
![screenshot 1](https://user-images.githubusercontent.com/3276261/36638783-1f42803e-19dc-11e8-828a-8e8eec975312.jpg)

 The error is exacly this: **command 'pgsql.run' not found**.
![screenshot 2](https://user-images.githubusercontent.com/3276261/36638784-1fb0fb04-19dc-11e8-8959-137c50c70229.jpg)

Server is offline, but psql works perfectly.
![screenshot 3](https://user-images.githubusercontent.com/3276261/36638795-57490106-19dc-11e8-9e3b-b918f55771d8.jpg)

**Comment by incompletude** [comment]
Just found the bug. I had a vscode temp file opened for days. I then installed the pgsql extension. For some reason, it could not hook to that file even after restarting the entire system (vscode brings it back from memory or from a temp file, the very reason i like it). Once I closed the file and created a physical .sql file everything worked properly.

Sorry for the trouble, thank you for all your help. Please, close the issue.

**Comment by rardoz** [comment]
Very weird. Same problem. Thanks @incompletude. I didn't have a temp file like you. I just created a new file called test.sql and ran it with a simple select. The other files are .pgsql files. These just started working after I ran it with a sql file.
