### ISSUE TITLE
Cannot read property 'context' of null

### ISSUE THREAD

**Issue by rahulsharma841990** [doublefint/vscode-pgsql#5]
When i trying to connect with PGSql Database is showing me error:

![image](https://user-images.githubusercontent.com/6939188/41197187-767be37a-6c72-11e8-83d1-ebf73e2ab80c.png)

**Comment by doublefint** [comment]
Hi, Rahul! But how can you see in error description, **this is not my extension** - "ckolkman.vscode-postgres-1.0.9". My is "doublefint.vscode-pgsql". I can't even find it on the vscode [marketplace](https://marketplace.visualstudio.com/search?term=vscode-postgres&target=VSCode&category=All%20categories&sortBy=Relevance)
