### ISSUE TITLE
Add entries to tmLanguage

### ISSUE THREAD

**Issue by phrohdoh** [doublefint/vscode-pgsql#6]
- [ ] `TIMESTAMP`
- [ ] `NOT`
- [ ] `USING`
- [ ] `EXISTS`
- [ ] `INDEX`
- [ ] `UNIQUE`
- [x] `JSON`
- [x] `JSONB`
- [x] `BIGSERIAL`
- [ ] `INT`
- [ ] `TRIGGER`
- [ ] `FOR`
- [ ] `EACH`

**Comment by doublefint** [comment]
Thank you, Phrohdoh! Added JSON, JSONB, BIGSERIAL
