### ISSUE TITLE
can I look up this in vscode too ?

### ISSUE THREAD

**Issue by vegarringdal** [doublefint/vscode-pgsql#7]
can I look up this in vscode too ?
or only old version there ?

**Comment by doublefint** [comment]
What do you mean? Can you explain more?

**Comment by vegarringdal** [comment]
though this was code for a vscode extension newer then the one you find in vscode
got tricked by:
`This extension is fixed clone of postgresql by JPTarquino`

sorry :-)

**Comment by vegarringdal** [comment]
btw, do you know about any postgres sql formater and linter for sql in vscode?
